version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Common package
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Converter package
  - package-ecosystem: "npm"
    directory: "/packages/converter"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Generator package
  - package-ecosystem: "npm"
    directory: "/packages/generator"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Manipulator package
  - package-ecosystem: "npm"
    directory: "/packages/manipulator"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Schemas package
  - package-ecosystem: "npm"
    directory: "/packages/schemas"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      lucide-packages:
        patterns:
          - "lucide*"
        update-types:
          - "minor"
          - "patch"
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # UI package
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      lucide-packages:
        patterns:
          - "lucide*"
        update-types:
          - "minor"
          - "patch"
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Playground
  - package-ecosystem: "npm"
    directory: "/playground"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      lucide-packages:
        patterns:
          - "lucide*"
        update-types:
          - "minor"
          - "patch"
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # Website
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
  
  # PDF-lib package
  - package-ecosystem: "npm"
    directory: "/packages/pdf-lib"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "npm"
    groups:
      eslint-packages:
        patterns:
          - "eslint*"
          - "@typescript-eslint*"
        update-types:
          - "minor"
          - "patch"
