name: Bug Report
description: Create a report with a procedure for reproducing the bug
labels:
  - "bug"
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Provide complete, executable code that can be used to reproduce the bug (e.g. a git repo, ZIP file, or JSFiddle). You must attach (or provide links to) any PDFs, images, or other files necessary to run your code.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Your Environment
      description: A clear and concise description of your environment
      value: |
        - pdfme package(@pdfme/generator or @pdfme/ui):
        - pdfme version:
        - Operating system:
        - Node.js version or Browser name & version:
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Your Error Log
      description: Write your ALL error log here
      render: shell
    validations:
      required: true
  - type: textarea
    id: addtional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false