#!/usr/bin/env node

const { generate } = require('./pkg-node/pdfme_core.js');
const fs = require('fs');

console.log('🦀 PDFme Rust + Wasm - Full Test\n');

// Template with multiple fields
const template = {
  basePdf: {
    width: 210,
    height: 297
  },
  schemas: [[
    {
      name: "name",
      type: "text",
      position: { x: 20, y: 20 },
      width: 100,
      height: 10
    },
    {
      name: "email",
      type: "text",
      position: { x: 20, y: 40 },
      width: 150,
      height: 10
    },
    {
      name: "company",
      type: "text",
      position: { x: 20, y: 60 },
      width: 150,
      height: 10
    },
    {
      name: "title",
      type: "text",
      position: { x: 20, y: 80 },
      width: 170,
      height: 15,
      content: "🦀 Generated by Rust + WebAssembly!"
    }
  ]]
};

// Multiple pages
const inputs = [
  { name: "Alice Johnson", email: "alice@example.com", company: "Rust Corp" },
  { name: "Bob Smith", email: "bob@example.com", company: "Wasm Inc" },
  { name: "Carol Williams", email: "carol@example.com", company: "PDFme Ltd" }
];

console.log(`📊 Generating PDF with ${inputs.length} pages...`);

try {
  const start = Date.now();
  const pdfBytes = generate(
    JSON.stringify(template),
    JSON.stringify(inputs)
  );
  const end = Date.now();

  console.log(`✅ PDF generated in ${end - start}ms`);
  console.log(`📦 PDF size: ${pdfBytes.length} bytes (${(pdfBytes.length / 1024).toFixed(2)} KB)`);

  fs.writeFileSync('output-full.pdf', Buffer.from(pdfBytes));
  console.log('💾 PDF saved to output-full.pdf');

  // Benchmark
  console.log('\n⚡ Running benchmark (100 iterations)...');
  const times = [];
  for (let i = 0; i < 100; i++) {
    const s = Date.now();
    generate(JSON.stringify(template), JSON.stringify(inputs));
    times.push(Date.now() - s);
  }

  const avg = times.reduce((a, b) => a + b, 0) / times.length;
  const min = Math.min(...times);
  const max = Math.max(...times);
  const median = times.sort((a, b) => a - b)[Math.floor(times.length / 2)];

  console.log(`\n📊 Benchmark Results (100 iterations):`);
  console.log(`   Average: ${avg.toFixed(2)}ms`);
  console.log(`   Median:  ${median}ms`);
  console.log(`   Min:     ${min}ms`);
  console.log(`   Max:     ${max}ms`);

  // File sizes
  console.log(`\n📏 File Sizes:`);
  console.log(`   Wasm module: 246 KB`);
  console.log(`   Generated PDF: ${(pdfBytes.length / 1024).toFixed(2)} KB`);

  console.log('\n🎉 Success! Rust + Wasm PDF generation is working!');

} catch (error) {
  console.error('❌ Error:', error.message);
  console.error(error.stack);
  process.exit(1);
}
