#!/usr/bin/env python3
"""
PDFme Rust + Python Demo

Shows how to use the Rust-powered PDF generation library from Python.
No JavaScript runtime required!
"""

import time
import pdfme

def format_bytes(bytes_size):
    """Format bytes to human readable string"""
    if bytes_size < 1024:
        return f"{bytes_size} B"
    elif bytes_size < 1024 * 1024:
        return f"{bytes_size / 1024:.2f} KB"
    else:
        return f"{bytes_size / (1024 * 1024):.2f} MB"


def main():
    print("🦀 PDFme Rust + Python Demo\n")

    # Template definition
    template = {
        "basePdf": {
            "width": 210,
            "height": 297
        },
        "schemas": [[
            {
                "name": "name",
                "type": "text",
                "position": {"x": 20, "y": 20},
                "width": 100,
                "height": 10
            },
            {
                "name": "email",
                "type": "text",
                "position": {"x": 20, "y": 40},
                "width": 150,
                "height": 10
            },
            {
                "name": "company",
                "type": "text",
                "position": {"x": 20, "y": 60},
                "width": 150,
                "height": 10
            },
            {
                "name": "title",
                "type": "text",
                "position": {"x": 20, "y": 80},
                "width": 170,
                "height": 15,
                "content": "Invoice - Generated by Rust from Python!"
            }
        ]]
    }

    # Input data
    inputs = [
        {
            "name": "Alice Johnson",
            "email": "alice@python.org",
            "company": "Python Foundation"
        },
        {
            "name": "Bob Williams",
            "email": "bob@django.com",
            "company": "Django Software"
        },
        {
            "name": "Carol Davis",
            "email": "carol@flask.io",
            "company": "Flask Framework"
        }
    ]

    print(f"📊 Generating PDF for {len(inputs)} records...\n")

    try:
        # Generate PDF
        start = time.time()
        pdf_bytes = pdfme.generate(template, inputs)
        end = time.time()

        generation_time = (end - start) * 1000  # Convert to ms

        # Save to file
        output_path = "output-python.pdf"
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)

        print(f"✅ PDF saved to: {output_path}")
        print(f"📦 PDF size: {format_bytes(len(pdf_bytes))}")
        print(f"⏱️  Generation time: {generation_time:.2f}ms\n")

        # Benchmark
        print("⚡ Running benchmark (100 iterations)...")
        iterations = 100
        times = []

        for _ in range(iterations):
            start = time.time()
            pdfme.generate(template, inputs)
            end = time.time()
            times.append((end - start) * 1000)

        avg = sum(times) / len(times)
        times_sorted = sorted(times)
        median = times_sorted[len(times) // 2]
        min_time = min(times)
        max_time = max(times)

        print(f"\n📊 Benchmark Results ({iterations} iterations):")
        print(f"   Average: {avg:.2f}ms")
        print(f"   Median:  {median:.2f}ms")
        print(f"   Min:     {min_time:.2f}ms")
        print(f"   Max:     {max_time:.2f}ms")

        print("\n🎉 Success! PDF generation from Python using Rust + Wasm!")
        print("\n💡 Use Cases:")
        print("   - Django/Flask web applications")
        print("   - FastAPI microservices")
        print("   - Data science pipelines")
        print("   - Automated report generation")
        print("   - No Node.js required!")

    except Exception as e:
        print(f"❌ Error: {e}")
        return 1

    return 0


if __name__ == "__main__":
    exit(main())
